//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleBibliothecaire.BiblioServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Livre", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Livre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string auteurField;
        
        private int isbnField;
        
        private int nbExemplaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string editeurField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string titre {
            get {
                return this.titreField;
            }
            set {
                if ((object.ReferenceEquals(this.titreField, value) != true)) {
                    this.titreField = value;
                    this.RaisePropertyChanged("titre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string auteur {
            get {
                return this.auteurField;
            }
            set {
                if ((object.ReferenceEquals(this.auteurField, value) != true)) {
                    this.auteurField = value;
                    this.RaisePropertyChanged("auteur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int isbn {
            get {
                return this.isbnField;
            }
            set {
                if ((this.isbnField.Equals(value) != true)) {
                    this.isbnField = value;
                    this.RaisePropertyChanged("isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int nbExemplaire {
            get {
                return this.nbExemplaireField;
            }
            set {
                if ((this.nbExemplaireField.Equals(value) != true)) {
                    this.nbExemplaireField = value;
                    this.RaisePropertyChanged("nbExemplaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string editeur {
            get {
                return this.editeurField;
            }
            set {
                if ((object.ReferenceEquals(this.editeurField, value) != true)) {
                    this.editeurField = value;
                    this.RaisePropertyChanged("editeur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Utilisateur", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleBibliothecaire.BiblioServiceReference.Bibliothecaire))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleBibliothecaire.BiblioServiceReference.Inscrit))]
    public partial class Utilisateur : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mdpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string mdp {
            get {
                return this.mdpField;
            }
            set {
                if ((object.ReferenceEquals(this.mdpField, value) != true)) {
                    this.mdpField = value;
                    this.RaisePropertyChanged("mdp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bibliothecaire", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Bibliothecaire : ConsoleBibliothecaire.BiblioServiceReference.Utilisateur {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inscrit", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Inscrit : ConsoleBibliothecaire.BiblioServiceReference.Utilisateur {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BiblioServiceReference.BiblioServiceSoap")]
    public interface BiblioServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ConsoleBibliothecaire.BiblioServiceReference.HelloWorldResponse HelloWorld(ConsoleBibliothecaire.BiblioServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name afficherUtilisateursResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/afficherUtilisateurs", ReplyAction="*")]
        ConsoleBibliothecaire.BiblioServiceReference.afficherUtilisateursResponse afficherUtilisateurs(ConsoleBibliothecaire.BiblioServiceReference.afficherUtilisateursRequest request);
        
        // CODEGEN: Generating message contract since element name afficherLivresResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/afficherLivres", ReplyAction="*")]
        ConsoleBibliothecaire.BiblioServiceReference.afficherLivresResponse afficherLivres(ConsoleBibliothecaire.BiblioServiceReference.afficherLivresRequest request);
        
        // CODEGEN: Generating message contract since element name livre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLivreDescription", ReplyAction="*")]
        ConsoleBibliothecaire.BiblioServiceReference.getLivreDescriptionResponse getLivreDescription(ConsoleBibliothecaire.BiblioServiceReference.getLivreDescriptionRequest request);
        
        // CODEGEN: Generating message contract since element name auteur from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rechercheParAuteur", ReplyAction="*")]
        ConsoleBibliothecaire.BiblioServiceReference.rechercheParAuteurResponse rechercheParAuteur(ConsoleBibliothecaire.BiblioServiceReference.rechercheParAuteurRequest request);
        
        // CODEGEN: Generating message contract since element name rechercheParISBNResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rechercheParISBN", ReplyAction="*")]
        ConsoleBibliothecaire.BiblioServiceReference.rechercheParISBNResponse rechercheParISBN(ConsoleBibliothecaire.BiblioServiceReference.rechercheParISBNRequest request);
        
        // CODEGEN: Generating message contract since element name inscrit from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publierCommentaire", ReplyAction="*")]
        ConsoleBibliothecaire.BiblioServiceReference.publierCommentaireResponse publierCommentaire(ConsoleBibliothecaire.BiblioServiceReference.publierCommentaireRequest request);
        
        // CODEGEN: Generating message contract since element name mdp from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/authentificationInscrit", ReplyAction="*")]
        ConsoleBibliothecaire.BiblioServiceReference.authentificationInscritResponse authentificationInscrit(ConsoleBibliothecaire.BiblioServiceReference.authentificationInscritRequest request);
        
        // CODEGEN: Generating message contract since element name nom from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/inscription", ReplyAction="*")]
        ConsoleBibliothecaire.BiblioServiceReference.inscriptionResponse inscription(ConsoleBibliothecaire.BiblioServiceReference.inscriptionRequest request);
        
        // CODEGEN: Generating message contract since element name mdp from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/authentificationBibliothecaire", ReplyAction="*")]
        ConsoleBibliothecaire.BiblioServiceReference.authentificationBibliothecaireResponse authentificationBibliothecaire(ConsoleBibliothecaire.BiblioServiceReference.authentificationBibliothecaireRequest request);
        
        // CODEGEN: Generating message contract since element name bibliothecaire from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ajoutInscrit", ReplyAction="*")]
        ConsoleBibliothecaire.BiblioServiceReference.ajoutInscritResponse ajoutInscrit(ConsoleBibliothecaire.BiblioServiceReference.ajoutInscritRequest request);
        
        // CODEGEN: Generating message contract since element name bibliothecaire from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ajoutLivre", ReplyAction="*")]
        ConsoleBibliothecaire.BiblioServiceReference.ajoutLivreResponse ajoutLivre(ConsoleBibliothecaire.BiblioServiceReference.ajoutLivreRequest request);
        
        // CODEGEN: Generating message contract since element name bibliothecaire from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retirerLivre", ReplyAction="*")]
        ConsoleBibliothecaire.BiblioServiceReference.retirerLivreResponse retirerLivre(ConsoleBibliothecaire.BiblioServiceReference.retirerLivreRequest request);
        
        // CODEGEN: Generating message contract since element name bibliothecaire from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retirerUtilisateur", ReplyAction="*")]
        ConsoleBibliothecaire.BiblioServiceReference.retirerUtilisateurResponse retirerUtilisateur(ConsoleBibliothecaire.BiblioServiceReference.retirerUtilisateurRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsoleBibliothecaire.BiblioServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsoleBibliothecaire.BiblioServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class afficherUtilisateursRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="afficherUtilisateurs", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.afficherUtilisateursRequestBody Body;
        
        public afficherUtilisateursRequest() {
        }
        
        public afficherUtilisateursRequest(ConsoleBibliothecaire.BiblioServiceReference.afficherUtilisateursRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class afficherUtilisateursRequestBody {
        
        public afficherUtilisateursRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class afficherUtilisateursResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="afficherUtilisateursResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.afficherUtilisateursResponseBody Body;
        
        public afficherUtilisateursResponse() {
        }
        
        public afficherUtilisateursResponse(ConsoleBibliothecaire.BiblioServiceReference.afficherUtilisateursResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class afficherUtilisateursResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string afficherUtilisateursResult;
        
        public afficherUtilisateursResponseBody() {
        }
        
        public afficherUtilisateursResponseBody(string afficherUtilisateursResult) {
            this.afficherUtilisateursResult = afficherUtilisateursResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class afficherLivresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="afficherLivres", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.afficherLivresRequestBody Body;
        
        public afficherLivresRequest() {
        }
        
        public afficherLivresRequest(ConsoleBibliothecaire.BiblioServiceReference.afficherLivresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class afficherLivresRequestBody {
        
        public afficherLivresRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class afficherLivresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="afficherLivresResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.afficherLivresResponseBody Body;
        
        public afficherLivresResponse() {
        }
        
        public afficherLivresResponse(ConsoleBibliothecaire.BiblioServiceReference.afficherLivresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class afficherLivresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string afficherLivresResult;
        
        public afficherLivresResponseBody() {
        }
        
        public afficherLivresResponseBody(string afficherLivresResult) {
            this.afficherLivresResult = afficherLivresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLivreDescriptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLivreDescription", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.getLivreDescriptionRequestBody Body;
        
        public getLivreDescriptionRequest() {
        }
        
        public getLivreDescriptionRequest(ConsoleBibliothecaire.BiblioServiceReference.getLivreDescriptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getLivreDescriptionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.Livre livre;
        
        public getLivreDescriptionRequestBody() {
        }
        
        public getLivreDescriptionRequestBody(ConsoleBibliothecaire.BiblioServiceReference.Livre livre) {
            this.livre = livre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLivreDescriptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLivreDescriptionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.getLivreDescriptionResponseBody Body;
        
        public getLivreDescriptionResponse() {
        }
        
        public getLivreDescriptionResponse(ConsoleBibliothecaire.BiblioServiceReference.getLivreDescriptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getLivreDescriptionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getLivreDescriptionResult;
        
        public getLivreDescriptionResponseBody() {
        }
        
        public getLivreDescriptionResponseBody(string getLivreDescriptionResult) {
            this.getLivreDescriptionResult = getLivreDescriptionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class rechercheParAuteurRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="rechercheParAuteur", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.rechercheParAuteurRequestBody Body;
        
        public rechercheParAuteurRequest() {
        }
        
        public rechercheParAuteurRequest(ConsoleBibliothecaire.BiblioServiceReference.rechercheParAuteurRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class rechercheParAuteurRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string auteur;
        
        public rechercheParAuteurRequestBody() {
        }
        
        public rechercheParAuteurRequestBody(string auteur) {
            this.auteur = auteur;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class rechercheParAuteurResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="rechercheParAuteurResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.rechercheParAuteurResponseBody Body;
        
        public rechercheParAuteurResponse() {
        }
        
        public rechercheParAuteurResponse(ConsoleBibliothecaire.BiblioServiceReference.rechercheParAuteurResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class rechercheParAuteurResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.Livre[] rechercheParAuteurResult;
        
        public rechercheParAuteurResponseBody() {
        }
        
        public rechercheParAuteurResponseBody(ConsoleBibliothecaire.BiblioServiceReference.Livre[] rechercheParAuteurResult) {
            this.rechercheParAuteurResult = rechercheParAuteurResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class rechercheParISBNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="rechercheParISBN", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.rechercheParISBNRequestBody Body;
        
        public rechercheParISBNRequest() {
        }
        
        public rechercheParISBNRequest(ConsoleBibliothecaire.BiblioServiceReference.rechercheParISBNRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class rechercheParISBNRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int isbn;
        
        public rechercheParISBNRequestBody() {
        }
        
        public rechercheParISBNRequestBody(int isbn) {
            this.isbn = isbn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class rechercheParISBNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="rechercheParISBNResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.rechercheParISBNResponseBody Body;
        
        public rechercheParISBNResponse() {
        }
        
        public rechercheParISBNResponse(ConsoleBibliothecaire.BiblioServiceReference.rechercheParISBNResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class rechercheParISBNResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.Livre rechercheParISBNResult;
        
        public rechercheParISBNResponseBody() {
        }
        
        public rechercheParISBNResponseBody(ConsoleBibliothecaire.BiblioServiceReference.Livre rechercheParISBNResult) {
            this.rechercheParISBNResult = rechercheParISBNResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publierCommentaireRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publierCommentaire", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.publierCommentaireRequestBody Body;
        
        public publierCommentaireRequest() {
        }
        
        public publierCommentaireRequest(ConsoleBibliothecaire.BiblioServiceReference.publierCommentaireRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publierCommentaireRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.Inscrit inscrit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contenu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ConsoleBibliothecaire.BiblioServiceReference.Livre livre;
        
        public publierCommentaireRequestBody() {
        }
        
        public publierCommentaireRequestBody(ConsoleBibliothecaire.BiblioServiceReference.Inscrit inscrit, string contenu, ConsoleBibliothecaire.BiblioServiceReference.Livre livre) {
            this.inscrit = inscrit;
            this.contenu = contenu;
            this.livre = livre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publierCommentaireResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publierCommentaireResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.publierCommentaireResponseBody Body;
        
        public publierCommentaireResponse() {
        }
        
        public publierCommentaireResponse(ConsoleBibliothecaire.BiblioServiceReference.publierCommentaireResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publierCommentaireResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string publierCommentaireResult;
        
        public publierCommentaireResponseBody() {
        }
        
        public publierCommentaireResponseBody(string publierCommentaireResult) {
            this.publierCommentaireResult = publierCommentaireResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authentificationInscritRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="authentificationInscrit", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.authentificationInscritRequestBody Body;
        
        public authentificationInscritRequest() {
        }
        
        public authentificationInscritRequest(ConsoleBibliothecaire.BiblioServiceReference.authentificationInscritRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class authentificationInscritRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mdp;
        
        public authentificationInscritRequestBody() {
        }
        
        public authentificationInscritRequestBody(int id, string mdp) {
            this.id = id;
            this.mdp = mdp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authentificationInscritResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="authentificationInscritResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.authentificationInscritResponseBody Body;
        
        public authentificationInscritResponse() {
        }
        
        public authentificationInscritResponse(ConsoleBibliothecaire.BiblioServiceReference.authentificationInscritResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class authentificationInscritResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.Inscrit authentificationInscritResult;
        
        public authentificationInscritResponseBody() {
        }
        
        public authentificationInscritResponseBody(ConsoleBibliothecaire.BiblioServiceReference.Inscrit authentificationInscritResult) {
            this.authentificationInscritResult = authentificationInscritResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inscriptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="inscription", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.inscriptionRequestBody Body;
        
        public inscriptionRequest() {
        }
        
        public inscriptionRequest(ConsoleBibliothecaire.BiblioServiceReference.inscriptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class inscriptionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mdp;
        
        public inscriptionRequestBody() {
        }
        
        public inscriptionRequestBody(string nom, string mdp) {
            this.nom = nom;
            this.mdp = mdp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inscriptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="inscriptionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.inscriptionResponseBody Body;
        
        public inscriptionResponse() {
        }
        
        public inscriptionResponse(ConsoleBibliothecaire.BiblioServiceReference.inscriptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class inscriptionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int inscriptionResult;
        
        public inscriptionResponseBody() {
        }
        
        public inscriptionResponseBody(int inscriptionResult) {
            this.inscriptionResult = inscriptionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authentificationBibliothecaireRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="authentificationBibliothecaire", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.authentificationBibliothecaireRequestBody Body;
        
        public authentificationBibliothecaireRequest() {
        }
        
        public authentificationBibliothecaireRequest(ConsoleBibliothecaire.BiblioServiceReference.authentificationBibliothecaireRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class authentificationBibliothecaireRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mdp;
        
        public authentificationBibliothecaireRequestBody() {
        }
        
        public authentificationBibliothecaireRequestBody(int id, string mdp) {
            this.id = id;
            this.mdp = mdp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authentificationBibliothecaireResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="authentificationBibliothecaireResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.authentificationBibliothecaireResponseBody Body;
        
        public authentificationBibliothecaireResponse() {
        }
        
        public authentificationBibliothecaireResponse(ConsoleBibliothecaire.BiblioServiceReference.authentificationBibliothecaireResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class authentificationBibliothecaireResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.Bibliothecaire authentificationBibliothecaireResult;
        
        public authentificationBibliothecaireResponseBody() {
        }
        
        public authentificationBibliothecaireResponseBody(ConsoleBibliothecaire.BiblioServiceReference.Bibliothecaire authentificationBibliothecaireResult) {
            this.authentificationBibliothecaireResult = authentificationBibliothecaireResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ajoutInscritRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ajoutInscrit", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.ajoutInscritRequestBody Body;
        
        public ajoutInscritRequest() {
        }
        
        public ajoutInscritRequest(ConsoleBibliothecaire.BiblioServiceReference.ajoutInscritRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ajoutInscritRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.Bibliothecaire bibliothecaire;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mdp;
        
        public ajoutInscritRequestBody() {
        }
        
        public ajoutInscritRequestBody(ConsoleBibliothecaire.BiblioServiceReference.Bibliothecaire bibliothecaire, string nom, string mdp) {
            this.bibliothecaire = bibliothecaire;
            this.nom = nom;
            this.mdp = mdp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ajoutInscritResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ajoutInscritResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.ajoutInscritResponseBody Body;
        
        public ajoutInscritResponse() {
        }
        
        public ajoutInscritResponse(ConsoleBibliothecaire.BiblioServiceReference.ajoutInscritResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ajoutInscritResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ajoutInscritResult;
        
        public ajoutInscritResponseBody() {
        }
        
        public ajoutInscritResponseBody(string ajoutInscritResult) {
            this.ajoutInscritResult = ajoutInscritResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ajoutLivreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ajoutLivre", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.ajoutLivreRequestBody Body;
        
        public ajoutLivreRequest() {
        }
        
        public ajoutLivreRequest(ConsoleBibliothecaire.BiblioServiceReference.ajoutLivreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ajoutLivreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.Bibliothecaire bibliothecaire;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string titre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string auteur;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int isbn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int nbExemplaire;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string editeur;
        
        public ajoutLivreRequestBody() {
        }
        
        public ajoutLivreRequestBody(ConsoleBibliothecaire.BiblioServiceReference.Bibliothecaire bibliothecaire, string titre, string auteur, int isbn, int nbExemplaire, string editeur) {
            this.bibliothecaire = bibliothecaire;
            this.titre = titre;
            this.auteur = auteur;
            this.isbn = isbn;
            this.nbExemplaire = nbExemplaire;
            this.editeur = editeur;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ajoutLivreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ajoutLivreResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.ajoutLivreResponseBody Body;
        
        public ajoutLivreResponse() {
        }
        
        public ajoutLivreResponse(ConsoleBibliothecaire.BiblioServiceReference.ajoutLivreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ajoutLivreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ajoutLivreResult;
        
        public ajoutLivreResponseBody() {
        }
        
        public ajoutLivreResponseBody(string ajoutLivreResult) {
            this.ajoutLivreResult = ajoutLivreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retirerLivreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="retirerLivre", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.retirerLivreRequestBody Body;
        
        public retirerLivreRequest() {
        }
        
        public retirerLivreRequest(ConsoleBibliothecaire.BiblioServiceReference.retirerLivreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class retirerLivreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.Bibliothecaire bibliothecaire;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string titre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string auteur;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string editeur;
        
        public retirerLivreRequestBody() {
        }
        
        public retirerLivreRequestBody(ConsoleBibliothecaire.BiblioServiceReference.Bibliothecaire bibliothecaire, string titre, string auteur, string editeur) {
            this.bibliothecaire = bibliothecaire;
            this.titre = titre;
            this.auteur = auteur;
            this.editeur = editeur;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retirerLivreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="retirerLivreResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.retirerLivreResponseBody Body;
        
        public retirerLivreResponse() {
        }
        
        public retirerLivreResponse(ConsoleBibliothecaire.BiblioServiceReference.retirerLivreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class retirerLivreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string retirerLivreResult;
        
        public retirerLivreResponseBody() {
        }
        
        public retirerLivreResponseBody(string retirerLivreResult) {
            this.retirerLivreResult = retirerLivreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retirerUtilisateurRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="retirerUtilisateur", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.retirerUtilisateurRequestBody Body;
        
        public retirerUtilisateurRequest() {
        }
        
        public retirerUtilisateurRequest(ConsoleBibliothecaire.BiblioServiceReference.retirerUtilisateurRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class retirerUtilisateurRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.Bibliothecaire bibliothecaire;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nom;
        
        public retirerUtilisateurRequestBody() {
        }
        
        public retirerUtilisateurRequestBody(ConsoleBibliothecaire.BiblioServiceReference.Bibliothecaire bibliothecaire, int id, string nom) {
            this.bibliothecaire = bibliothecaire;
            this.id = id;
            this.nom = nom;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retirerUtilisateurResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="retirerUtilisateurResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleBibliothecaire.BiblioServiceReference.retirerUtilisateurResponseBody Body;
        
        public retirerUtilisateurResponse() {
        }
        
        public retirerUtilisateurResponse(ConsoleBibliothecaire.BiblioServiceReference.retirerUtilisateurResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class retirerUtilisateurResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string retirerUtilisateurResult;
        
        public retirerUtilisateurResponseBody() {
        }
        
        public retirerUtilisateurResponseBody(string retirerUtilisateurResult) {
            this.retirerUtilisateurResult = retirerUtilisateurResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BiblioServiceSoapChannel : ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BiblioServiceSoapClient : System.ServiceModel.ClientBase<ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap>, ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap {
        
        public BiblioServiceSoapClient() {
        }
        
        public BiblioServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BiblioServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiblioServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiblioServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleBibliothecaire.BiblioServiceReference.HelloWorldResponse ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap.HelloWorld(ConsoleBibliothecaire.BiblioServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsoleBibliothecaire.BiblioServiceReference.HelloWorldRequest inValue = new ConsoleBibliothecaire.BiblioServiceReference.HelloWorldRequest();
            inValue.Body = new ConsoleBibliothecaire.BiblioServiceReference.HelloWorldRequestBody();
            ConsoleBibliothecaire.BiblioServiceReference.HelloWorldResponse retVal = ((ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleBibliothecaire.BiblioServiceReference.afficherUtilisateursResponse ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap.afficherUtilisateurs(ConsoleBibliothecaire.BiblioServiceReference.afficherUtilisateursRequest request) {
            return base.Channel.afficherUtilisateurs(request);
        }
        
        public string afficherUtilisateurs() {
            ConsoleBibliothecaire.BiblioServiceReference.afficherUtilisateursRequest inValue = new ConsoleBibliothecaire.BiblioServiceReference.afficherUtilisateursRequest();
            inValue.Body = new ConsoleBibliothecaire.BiblioServiceReference.afficherUtilisateursRequestBody();
            ConsoleBibliothecaire.BiblioServiceReference.afficherUtilisateursResponse retVal = ((ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap)(this)).afficherUtilisateurs(inValue);
            return retVal.Body.afficherUtilisateursResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleBibliothecaire.BiblioServiceReference.afficherLivresResponse ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap.afficherLivres(ConsoleBibliothecaire.BiblioServiceReference.afficherLivresRequest request) {
            return base.Channel.afficherLivres(request);
        }
        
        public string afficherLivres() {
            ConsoleBibliothecaire.BiblioServiceReference.afficherLivresRequest inValue = new ConsoleBibliothecaire.BiblioServiceReference.afficherLivresRequest();
            inValue.Body = new ConsoleBibliothecaire.BiblioServiceReference.afficherLivresRequestBody();
            ConsoleBibliothecaire.BiblioServiceReference.afficherLivresResponse retVal = ((ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap)(this)).afficherLivres(inValue);
            return retVal.Body.afficherLivresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleBibliothecaire.BiblioServiceReference.getLivreDescriptionResponse ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap.getLivreDescription(ConsoleBibliothecaire.BiblioServiceReference.getLivreDescriptionRequest request) {
            return base.Channel.getLivreDescription(request);
        }
        
        public string getLivreDescription(ConsoleBibliothecaire.BiblioServiceReference.Livre livre) {
            ConsoleBibliothecaire.BiblioServiceReference.getLivreDescriptionRequest inValue = new ConsoleBibliothecaire.BiblioServiceReference.getLivreDescriptionRequest();
            inValue.Body = new ConsoleBibliothecaire.BiblioServiceReference.getLivreDescriptionRequestBody();
            inValue.Body.livre = livre;
            ConsoleBibliothecaire.BiblioServiceReference.getLivreDescriptionResponse retVal = ((ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap)(this)).getLivreDescription(inValue);
            return retVal.Body.getLivreDescriptionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleBibliothecaire.BiblioServiceReference.rechercheParAuteurResponse ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap.rechercheParAuteur(ConsoleBibliothecaire.BiblioServiceReference.rechercheParAuteurRequest request) {
            return base.Channel.rechercheParAuteur(request);
        }
        
        public ConsoleBibliothecaire.BiblioServiceReference.Livre[] rechercheParAuteur(string auteur) {
            ConsoleBibliothecaire.BiblioServiceReference.rechercheParAuteurRequest inValue = new ConsoleBibliothecaire.BiblioServiceReference.rechercheParAuteurRequest();
            inValue.Body = new ConsoleBibliothecaire.BiblioServiceReference.rechercheParAuteurRequestBody();
            inValue.Body.auteur = auteur;
            ConsoleBibliothecaire.BiblioServiceReference.rechercheParAuteurResponse retVal = ((ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap)(this)).rechercheParAuteur(inValue);
            return retVal.Body.rechercheParAuteurResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleBibliothecaire.BiblioServiceReference.rechercheParISBNResponse ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap.rechercheParISBN(ConsoleBibliothecaire.BiblioServiceReference.rechercheParISBNRequest request) {
            return base.Channel.rechercheParISBN(request);
        }
        
        public ConsoleBibliothecaire.BiblioServiceReference.Livre rechercheParISBN(int isbn) {
            ConsoleBibliothecaire.BiblioServiceReference.rechercheParISBNRequest inValue = new ConsoleBibliothecaire.BiblioServiceReference.rechercheParISBNRequest();
            inValue.Body = new ConsoleBibliothecaire.BiblioServiceReference.rechercheParISBNRequestBody();
            inValue.Body.isbn = isbn;
            ConsoleBibliothecaire.BiblioServiceReference.rechercheParISBNResponse retVal = ((ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap)(this)).rechercheParISBN(inValue);
            return retVal.Body.rechercheParISBNResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleBibliothecaire.BiblioServiceReference.publierCommentaireResponse ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap.publierCommentaire(ConsoleBibliothecaire.BiblioServiceReference.publierCommentaireRequest request) {
            return base.Channel.publierCommentaire(request);
        }
        
        public string publierCommentaire(ConsoleBibliothecaire.BiblioServiceReference.Inscrit inscrit, string contenu, ConsoleBibliothecaire.BiblioServiceReference.Livre livre) {
            ConsoleBibliothecaire.BiblioServiceReference.publierCommentaireRequest inValue = new ConsoleBibliothecaire.BiblioServiceReference.publierCommentaireRequest();
            inValue.Body = new ConsoleBibliothecaire.BiblioServiceReference.publierCommentaireRequestBody();
            inValue.Body.inscrit = inscrit;
            inValue.Body.contenu = contenu;
            inValue.Body.livre = livre;
            ConsoleBibliothecaire.BiblioServiceReference.publierCommentaireResponse retVal = ((ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap)(this)).publierCommentaire(inValue);
            return retVal.Body.publierCommentaireResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleBibliothecaire.BiblioServiceReference.authentificationInscritResponse ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap.authentificationInscrit(ConsoleBibliothecaire.BiblioServiceReference.authentificationInscritRequest request) {
            return base.Channel.authentificationInscrit(request);
        }
        
        public ConsoleBibliothecaire.BiblioServiceReference.Inscrit authentificationInscrit(int id, string mdp) {
            ConsoleBibliothecaire.BiblioServiceReference.authentificationInscritRequest inValue = new ConsoleBibliothecaire.BiblioServiceReference.authentificationInscritRequest();
            inValue.Body = new ConsoleBibliothecaire.BiblioServiceReference.authentificationInscritRequestBody();
            inValue.Body.id = id;
            inValue.Body.mdp = mdp;
            ConsoleBibliothecaire.BiblioServiceReference.authentificationInscritResponse retVal = ((ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap)(this)).authentificationInscrit(inValue);
            return retVal.Body.authentificationInscritResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleBibliothecaire.BiblioServiceReference.inscriptionResponse ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap.inscription(ConsoleBibliothecaire.BiblioServiceReference.inscriptionRequest request) {
            return base.Channel.inscription(request);
        }
        
        public int inscription(string nom, string mdp) {
            ConsoleBibliothecaire.BiblioServiceReference.inscriptionRequest inValue = new ConsoleBibliothecaire.BiblioServiceReference.inscriptionRequest();
            inValue.Body = new ConsoleBibliothecaire.BiblioServiceReference.inscriptionRequestBody();
            inValue.Body.nom = nom;
            inValue.Body.mdp = mdp;
            ConsoleBibliothecaire.BiblioServiceReference.inscriptionResponse retVal = ((ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap)(this)).inscription(inValue);
            return retVal.Body.inscriptionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleBibliothecaire.BiblioServiceReference.authentificationBibliothecaireResponse ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap.authentificationBibliothecaire(ConsoleBibliothecaire.BiblioServiceReference.authentificationBibliothecaireRequest request) {
            return base.Channel.authentificationBibliothecaire(request);
        }
        
        public ConsoleBibliothecaire.BiblioServiceReference.Bibliothecaire authentificationBibliothecaire(int id, string mdp) {
            ConsoleBibliothecaire.BiblioServiceReference.authentificationBibliothecaireRequest inValue = new ConsoleBibliothecaire.BiblioServiceReference.authentificationBibliothecaireRequest();
            inValue.Body = new ConsoleBibliothecaire.BiblioServiceReference.authentificationBibliothecaireRequestBody();
            inValue.Body.id = id;
            inValue.Body.mdp = mdp;
            ConsoleBibliothecaire.BiblioServiceReference.authentificationBibliothecaireResponse retVal = ((ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap)(this)).authentificationBibliothecaire(inValue);
            return retVal.Body.authentificationBibliothecaireResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleBibliothecaire.BiblioServiceReference.ajoutInscritResponse ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap.ajoutInscrit(ConsoleBibliothecaire.BiblioServiceReference.ajoutInscritRequest request) {
            return base.Channel.ajoutInscrit(request);
        }
        
        public string ajoutInscrit(ConsoleBibliothecaire.BiblioServiceReference.Bibliothecaire bibliothecaire, string nom, string mdp) {
            ConsoleBibliothecaire.BiblioServiceReference.ajoutInscritRequest inValue = new ConsoleBibliothecaire.BiblioServiceReference.ajoutInscritRequest();
            inValue.Body = new ConsoleBibliothecaire.BiblioServiceReference.ajoutInscritRequestBody();
            inValue.Body.bibliothecaire = bibliothecaire;
            inValue.Body.nom = nom;
            inValue.Body.mdp = mdp;
            ConsoleBibliothecaire.BiblioServiceReference.ajoutInscritResponse retVal = ((ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap)(this)).ajoutInscrit(inValue);
            return retVal.Body.ajoutInscritResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleBibliothecaire.BiblioServiceReference.ajoutLivreResponse ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap.ajoutLivre(ConsoleBibliothecaire.BiblioServiceReference.ajoutLivreRequest request) {
            return base.Channel.ajoutLivre(request);
        }
        
        public string ajoutLivre(ConsoleBibliothecaire.BiblioServiceReference.Bibliothecaire bibliothecaire, string titre, string auteur, int isbn, int nbExemplaire, string editeur) {
            ConsoleBibliothecaire.BiblioServiceReference.ajoutLivreRequest inValue = new ConsoleBibliothecaire.BiblioServiceReference.ajoutLivreRequest();
            inValue.Body = new ConsoleBibliothecaire.BiblioServiceReference.ajoutLivreRequestBody();
            inValue.Body.bibliothecaire = bibliothecaire;
            inValue.Body.titre = titre;
            inValue.Body.auteur = auteur;
            inValue.Body.isbn = isbn;
            inValue.Body.nbExemplaire = nbExemplaire;
            inValue.Body.editeur = editeur;
            ConsoleBibliothecaire.BiblioServiceReference.ajoutLivreResponse retVal = ((ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap)(this)).ajoutLivre(inValue);
            return retVal.Body.ajoutLivreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleBibliothecaire.BiblioServiceReference.retirerLivreResponse ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap.retirerLivre(ConsoleBibliothecaire.BiblioServiceReference.retirerLivreRequest request) {
            return base.Channel.retirerLivre(request);
        }
        
        public string retirerLivre(ConsoleBibliothecaire.BiblioServiceReference.Bibliothecaire bibliothecaire, string titre, string auteur, string editeur) {
            ConsoleBibliothecaire.BiblioServiceReference.retirerLivreRequest inValue = new ConsoleBibliothecaire.BiblioServiceReference.retirerLivreRequest();
            inValue.Body = new ConsoleBibliothecaire.BiblioServiceReference.retirerLivreRequestBody();
            inValue.Body.bibliothecaire = bibliothecaire;
            inValue.Body.titre = titre;
            inValue.Body.auteur = auteur;
            inValue.Body.editeur = editeur;
            ConsoleBibliothecaire.BiblioServiceReference.retirerLivreResponse retVal = ((ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap)(this)).retirerLivre(inValue);
            return retVal.Body.retirerLivreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleBibliothecaire.BiblioServiceReference.retirerUtilisateurResponse ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap.retirerUtilisateur(ConsoleBibliothecaire.BiblioServiceReference.retirerUtilisateurRequest request) {
            return base.Channel.retirerUtilisateur(request);
        }
        
        public string retirerUtilisateur(ConsoleBibliothecaire.BiblioServiceReference.Bibliothecaire bibliothecaire, int id, string nom) {
            ConsoleBibliothecaire.BiblioServiceReference.retirerUtilisateurRequest inValue = new ConsoleBibliothecaire.BiblioServiceReference.retirerUtilisateurRequest();
            inValue.Body = new ConsoleBibliothecaire.BiblioServiceReference.retirerUtilisateurRequestBody();
            inValue.Body.bibliothecaire = bibliothecaire;
            inValue.Body.id = id;
            inValue.Body.nom = nom;
            ConsoleBibliothecaire.BiblioServiceReference.retirerUtilisateurResponse retVal = ((ConsoleBibliothecaire.BiblioServiceReference.BiblioServiceSoap)(this)).retirerUtilisateur(inValue);
            return retVal.Body.retirerUtilisateurResult;
        }
    }
}
